# Generated by Django 4.2.2 on 2024-01-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialInvoice',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('COMMERCIAL_NUMBER', models.CharField(max_length=100)),
                ('PACKING_LIST_NUMBER', models.CharField(max_length=100)),
                ('DATE', models.CharField(max_length=100)),
                ('VESSEL_NAME', models.CharField(max_length=100)),
                ('WES_NUMBER', models.CharField(max_length=100)),
                ('PO_NUMBER', models.CharField(max_length=100)),
                ('INCHARGE', models.CharField(max_length=100)),
                ('Remarks', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'commercial_invoice',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CommercialPacl',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('COMMERCIAL_NUMBER', models.CharField(max_length=100)),
                ('PACL_NUMBER', models.CharField(max_length=100)),
                ('DATE', models.CharField(max_length=100)),
                ('VESSEL_NAME', models.CharField(max_length=100)),
                ('WES_NUMBER', models.CharField(max_length=100)),
                ('PO_NUMBER', models.CharField(max_length=100)),
                ('INCHARGE', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'commercial_pacl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DHL',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('WES_Ref', models.CharField(max_length=100)),
                ('PO_NO', models.CharField(max_length=100)),
                ('Client_Name', models.CharField(max_length=100)),
                ('Ship_name', models.CharField(max_length=100)),
                ('Client_Invoice_No', models.CharField(max_length=100)),
                ('INVOICE_DATE', models.CharField(max_length=100)),
                ('Client_Frieght_Cost', models.CharField(max_length=100)),
                ('Client_Freight_Currency', models.CharField(max_length=100)),
                ('Client_Freight_Cost_in_SGD', models.CharField(max_length=100)),
                ('DHL_Invoice_number', models.CharField(max_length=100)),
                ('AWB_NUMBER', models.CharField(max_length=100)),
                ('AMOUNT_INR', models.CharField(max_length=100)),
                ('DHL_AMOUNT_SGD', models.CharField(max_length=100)),
                ('DHL_DUTY_TAX', models.CharField(max_length=100)),
                ('Invoice_date2', models.CharField(max_length=100)),
                ('Due_Date', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('Paid_date', models.CharField(max_length=100)),
                ('Transaction_number', models.CharField(max_length=100)),
                ('From_Country', models.CharField(max_length=100)),
                ('To_Country', models.CharField(max_length=100)),
                ('Weight_Kg', models.CharField(max_length=100)),
                ('Dimension_Volume', models.CharField(max_length=100)),
                ('Dimension_CM', models.CharField(max_length=100)),
                ('Profit_and_Loss', models.CharField(max_length=100)),
                ('Remarks', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dhl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DoDnNumber',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('DO_DN_NUMBER', models.CharField(max_length=100)),
                ('DATE', models.CharField(max_length=100)),
                ('VESSEL_NAME', models.CharField(max_length=100)),
                ('WES_NUMBER', models.CharField(max_length=100)),
                ('PO_NUMBER', models.CharField(max_length=100)),
                ('INCHARGE', models.CharField(max_length=100)),
                ('REMARK', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'do_dn_number',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DoNumber',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('DO_NUMBER', models.CharField(max_length=100)),
                ('DATE', models.CharField(max_length=100)),
                ('VESSEL_NAME', models.CharField(max_length=100)),
                ('WES_NUMBER', models.CharField(max_length=100)),
                ('PO_NUMBER', models.CharField(max_length=100)),
                ('INCHARGE', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'do_number',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ordertracking',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Branch', models.CharField(max_length=100)),
                ('WES_NO', models.CharField(max_length=100)),
                ('PO_NO', models.CharField(max_length=100)),
                ('PO_Date', models.CharField(max_length=100)),
                ('Client_Name', models.CharField(max_length=100)),
                ('Vessel_Name', models.CharField(max_length=100)),
                ('Supplier_Name', models.CharField(max_length=100)),
                ('Forwarder_name', models.CharField(max_length=100)),
                ('AWB_NO', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('Status_Date', models.CharField(max_length=100)),
                ('InCharger', models.CharField(max_length=100)),
                ('Dolibar', models.CharField(max_length=100)),
                ('Remarks', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'order_tracking',
                'managed': True,
            },
        ),
    ]
